@SET DEVENV_BOOST_VERSION=1_84_0
@SET DEVENV_BOOST_ARCH=lib64-msvc-14.2

@SET CMAKE_BOOST_ROOT=%DEVENV_ROOT%\libs\boost_%DEVENV_BOOST_VERSION%

@SET INCLUDE=%CMAKE_BOOST_ROOT%;%INCLUDE%
@SET LIB=%CMAKE_BOOST_ROOT%\%DEVENV_BOOST_ARCH%;%LIB%
@SET PATH=%CMAKE_BOOST_ROOT%\%DEVENV_BOOST_ARCH%;%PATH%

@%DEVENV_ECHO% "boost %DEVENV_BOOST_VERSION%/%DEVENV_BOOST_ARCH%"
@printf "  BOOST_VERSION="
@printf "#include <boost/version.hpp>\nBOOST_VERSION" | clang++ -E - | tail -n 1
